version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        #container_name: nginx
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/usr/share/nginx/html
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        ports:
            - 84:80
        networks:
            - packages
          
    phpfpm: 
        build: .docker/conf/fpm
        working_dir: /usr/share/nginx/html
        ports: 
            - 9004:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/usr/share/nginx/html
            - ${WEBSERVER}/${DIRECTORY}/bin/symfony:/usr/bin/symfony
        networks:
            - packages
    
    # haproxy:
    #     image: haproxy
    #     volumes:
    #         - ${WEBSERVER}/packages/docker/conf/haproxy/haproxy:/usr/local/etc/haproxy/haproxy.cfg
    
    # php-oauth-server:
    #     image: php:fpm
    #     container_name: php-oauth-server
    #     ports: 
    #         - 9008:9000
    #     volumes:
    #         - /WEBSERVER/packages:/usr/share/nginx/html
    
    # mariadb: 
    #     image: mariadb
    #     container_name: mariadb
    #     ports: 
    #         - 3306:3306
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: example
        # volumes: 
        #     - /WEBSERVER/packages/data:/var/lib/mysql
    
    # adminer:
    #     image: adminer
    #     container_name: mariadb-adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    
    #     - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
    #   - type: bind
    #     source: ./static
    #     target: /opt/app/static

    # minio:
    #     image: minio/minio
    #     container_name: minio
    #     ports:
    #         - 9999:9000
    
    #client
    #minio-mc:
    #    image: minio/mc
    
networks:
    packages:
        driver: bridge