version: '2.2'

services: 
    phpfpm: 
        image: packagesex-phpfpm:latest
        #build: .docker/Dockerfile/fpm
        working_dir: /usr/share/nginx/html
        ports: 
            - 9004:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/usr/share/nginx/html
            - ${WEBSERVER}/${DIRECTORY}/bin/symfony:/usr/bin/symfony
        networks:
            - packages

    nginx:
        image: nginx:1.17
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/usr/share/nginx/html
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        ports:
            - 84:80
        networks:
            - packages
    
    # haproxy:
    #     image: haproxy
    #     volumes:
    #         - ${WEBSERVER}/packages/docker/conf/haproxy/haproxy:/usr/local/etc/haproxy/haproxy.cfg
    
    # mariadb: 
    #     image: mariadb
    #     container_name: mariadb
    #     ports: 
    #         - 3306:3306
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: example
        # volumes: 
        #     - /WEBSERVER/packages/data:/var/lib/mysql
    
networks:
    packages:
        driver: bridge