version: '2.2'

services: 
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ${WEBSERVER}/packages:/usr/share/nginx/html
            - ${WEBSERVER}/packages/docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
          
    phpfpm: 
        build: ./conf/fpm
        container_name: phpfpm
        working_dir: /usr/share/nginx/html
        ports: 
            - 9000:9000
        volumes:
            - ${WEBSERVER}/packages:/usr/share/nginx/html
    
    # php-oauth-server:
    #     image: php:fpm
    #     container_name: php-oauth-server
    #     ports: 
    #         - 9008:9000
    #     volumes:
    #         - /WEBSERVER/packages:/usr/share/nginx/html
    
    mariadb: 
        image: mariadb
        container_name: mariadb
        ports: 
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        # volumes: 
        #     - /WEBSERVER/packages/data:/var/lib/mysql
    
    # adminer:
    #     image: adminer
    #     container_name: mariadb-adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    
    openldap:
        image: osixia/openldap
        container_name: ldap-server
        ports:
            - 389:389
            - 636:636
        environment:
            LDAP_ORGANISATION: "My Company"
            LDAP_DOMAIN: "my-company.com"
            LDAP_ADMIN_PASSWORD: "JonSn0w"
    
            # LDAP_BASE_DN
            # {{ LDAP_BACKEND }}
            # {{ LDAP_DOMAIN }}
            # {{ LDAP_READONLY_USER_USERNAME }}
            # {{ LDAP_READONLY_USER_PASSWORD_ENCRYPTED }
    
    ldap-admin: 
        image: osixia/phpldapadmin
        container_name: ldap-admin
    
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - 9999:9000
    