version: '2.2'

services: 
    nginx:
        image: nginx #1.17
        container_name: nginx
        volumes:
            - ${WEBSERVER}/packages:/usr/share/nginx/html
            - ${WEBSERVER}/packages/docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
          
    phpfpm: 
        build: ./conf/fpm
        container_name: phpfpm
        working_dir: /usr/share/nginx/html
        ports: 
            - 9000:9000
        volumes:
            - ${WEBSERVER}/packages:/usr/share/nginx/html
    
    # haproxy:
    #     image: haproxy
    #     volumes:
    #         - ${WEBSERVER}/packages/docker/conf/haproxy/haproxy:/usr/local/etc/haproxy/haproxy.cfg
    
    # php-oauth-server:
    #     image: php:fpm
    #     container_name: php-oauth-server
    #     ports: 
    #         - 9008:9000
    #     volumes:
    #         - /WEBSERVER/packages:/usr/share/nginx/html
    
    mariadb: 
        image: mariadb
        container_name: mariadb
        ports: 
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        # volumes: 
        #     - /WEBSERVER/packages/data:/var/lib/mysql
    
    # adminer:
    #     image: adminer
    #     container_name: mariadb-adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    
    ldap-server:
        image: osixia/openldap:1.2.5  #(openldap 2.4)
        container_name: ldap-server
        ports:
            - 389:389
            - 636:636
        environment:
            LDAP_ORGANISATION: "My Company"
            LDAP_DOMAIN: "my-company.com"
            LDAP_ADMIN_PASSWORD: "JonSn0w"
    #     - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
    #   - type: bind
    #     source: ./static
    #     target: /opt/app/static
            
            #for data persistance
            #LDAP_OPENLDAP_GID: 1234 
            #LDAP_OPENLDAP_UID: 2345
        # volumes: 
        #     - ${WEBSERVER}/packages/docker/data/ldap/lib:/var/lib/ldap
        #     - ${WEBSERVER}/packages/docker/data/ldap/slapd.d:/etc/ldap/slapd.d

            # LDAP_BASE_DN
            # {{ LDAP_BACKEND }}
            # {{ LDAP_DOMAIN }}
            # {{ LDAP_READONLY_USER_USERNAME }}
            # {{ LDAP_READONLY_USER_PASSWORD_ENCRYPTED }
    
    ldap-admin: 
        #http://phpldapadmin.sourceforge.net/wiki/index.php/LDAP_server_definitions
        #http://phpldapadmin.sourceforge.net/wiki/index.php/Config.php
        image: osixia/phpldapadmin:0.9.0 #phpLDAPadmin 1.2.5
        container_name: ldap-admin
        #login: cn=admin,dc=my-company,dc=com
        ports:
            - 6443:443
        #environment:
        #    PHPLDAPADMIN_LDAP_HOSTS: ldap-server
        #PHPLDAP_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" phpldapadmin-service)
        volumes:
            - ${WEBSERVER}/packages/docker/conf/ldapadmin/config.php:/container/service/phpldapadmin/assets/config/config.php
        command: --copy-service
    
    # minio:
    #     image: minio/minio
    #     container_name: minio
    #     ports:
    #         - 9999:9000
    
    #client
    #minio-mc:
    #    image: minio/mc
    