# #############
#
# https://www.oauth.com/playground/client-registration.html
# 
# #############

client_id: 0oaqou8vvhZ6THIW30h7
client_secret: -6x1bXMs4c4yzpwp1VHI9s-jYF6dfIv0zyuD6QaL

redirect_uri: https://www.oauth.com/playground/authorization-code.html
redirect_uri2: https://www.oauth.com/playground/authorization-code-with-pkce.html
https://www.oauth.com/playground/implicit.html
https://www.oauth.com/playground/oidc.html

supported_grant_types: authorization_code, refresh_token, implicit

login: foolish-owl@example.com
password: Healthy-Porpoise-Doubtful-Eland-7

# https://dev-396343.oktapreview.com/oauth2/default/v1/authorize?
#   response_type=code
#   &client_id=0oaqou8vvhZ6THIW30h7
#   &redirect_uri=https://www.oauth.com/playground/authorization-code.html
#   &scope=photo+offline_access
#   &state=eIh8JYcMr5sSGfix